### ISSUE TITLE
BORIS won't start

### ISSUE THREAD

**Issue by dangelov** [d11wtq/boris#29]
I get the following error when I try to start it. I cloned the repo, cd'ed and tried to run it.

Dinos-MacBook-Pro:bin dinoangelov$ ./boris

Fatal error: Call to undefined function Boris\pcntl_signal() in /Users/dinoangelov/Library/Developer/boris/lib/Boris/Boris.php on line 110

**Comment by Charleezy** [comment]
I commented out the line in my php.ini and then restarted apache. No dice. I still get the error. Welp.

**Comment by Pysis868** [comment]
Since I found this page from Google searching my problem, a bit different from dangelov's message: `PCNTL support seems to be missing or disabled. See https://github.com/d11wtq/boris/issues/29 for details`

Went through some kind of upgrade on the Mac.  I'm positive it was upgrades in (Home)`brew` when the php package/formula was being renamed to `php@5.6`, but somehow my shell started using the system `/usr/bin/php`, that mentioned above, lacks the compilation configuration to include PCNTL functions, along with many others.

I still had that PHP installed, but didn't have the paths set-up in my terminal (`fish`), so I just added them with the commands mentioned in the brew PHP package's info text.

Maybe I was using the system one this entire time until now, but that's strange because I was successfully using `boris` until this situation occurred.

**Comment by ernstki** [comment]
Hello from the future!

I discovered by way of [this Stack Overflow answer](https://stackoverflow.com/a/16483002/785213) that MacPorts and Homebrew both seem to have `phpXY-pcntl` packages available.

In my case, this let me use boris on my Mac running Mojave (10.14.6):

```
$ sudo port install php73-pcntl
--->  Computing dependencies for php73
⋮
--->  Some of the ports you installed have notes:
  php73 has the following notes:
    You may need to update your php.ini for any changes that have been made in this version of php73. Compare /opt/local/etc/php73/php.ini with
    /opt/local/etc/php73/php.ini-development (if this is a development server) or /opt/local/etc/php73/php.ini-production (if this is a production server).
  php73-pcntl has the following notes:
    php73-pcntl should not be enabled within a web server environment. Unexpected results may occur if any process control functions are used within a web server
    environment.

$ php -m | grep pcntl
pcntl
```

Note the warning that this version of PHP should not be used in a production environment, so just be aware of that. I'm only using the interpreter from the command line, so this was fine for me.

Hope this helps!

---

**Update**: It was also necessary to `sudo port install php73-posix`, otherwise I was getting errors like:

```
Fatal error: Uncaught Error: Call to undefined function Boris\posix_getpid() in /path/to/boris/lib/Boris/EvalWorker.php:113
Stack trace:
#0 /path/to/boris/lib/Boris/Boris.php(175): Boris\EvalWorker->start()
#1 /path/to/boris/bin/boris(18): Boris\Boris->start()
#2 {main}
  thrown in /path/to/boris/lib/Boris/EvalWorker.php on line 113
```
