### ISSUE TITLE
Key differences between Boris and PsySH?

### ISSUE THREAD

**Issue by tejasmanohar** [d11wtq/boris#94]
Let's outline key differences between Boris and PsySH in comments here. This would make for a good Wiki page later to help devs decide which REPL is fit for them.

**Comment by GrahamCampbell** [comment]
Boris doesn't work on windows due to its hard dependence on a php extension not available on windows.

**Comment by bobthecow** [comment]
## Key differences

<table><tbody>
<tr><th>PsySH</th><td><img alt="Made out of awesome" src="http://img.shields.io/badge/made_out_of_awesome-✓-brightgreen.svg?style=flat-square"></td></tr>
<tr><th>Boris</th><td><img alt="Yeah, it's nice, too" src="http://img.shields.io/badge/yeah,_it's_nice_too-✓-green.svg?style=flat-square"></td></tr>
</tbody></table>

;)

**Comment by tejasmanohar** [comment]
Lol, @bobthecow

**Comment by tejasmanohar** [comment]
Boris is super light-weight.

**Comment by tejasmanohar** [comment]
I think I have a good amount for a list (mostly from outside this thread) :+1:

**Comment by bobthecow** [comment]
I'd say, other than the "super awesome" / "yeah, it's pretty okay as well" distinction, the main differences are:

|                                        Boris                                         |                                           PsySH                                            |
|--------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------|
| **Is actually a REPL** You'd be surprised how many shells forget the **P** part.     | **Also a REPL** We should start an "actually a repl" bowling team.                         |
| **Light-weight** ~900 lines of code, does not depend on any other libraries.         | **Not-as-light-weight** ~6000 lines of code, depends on a couple of other libraries.       |
| **Relies on pcntl** Uses POSIX-only features to make your REPL experience not awful. | **Works with or without pcntl** Same, plus a fallback mode for non-POSIX systems (Windows) |
| **Relies on readline** Because you really don't want a REPL without readline.        | **Works with or without readline** Because sometimes you don't have a choice :(            |
| **PHP** !                                                                            | **PHP + commands** !!                                                                      |
| **?**                                                                                | **Input works even if it doesn't with a semicolon** :)                                     |

**Comment by tejasmanohar** [comment]
:+1: got it
